{% set name = "newt" %}
{% set version = "0.52.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://fedorahosted.org/releases/n/e/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: caa372907b14ececfe298f0d512a62f41d33b290610244a58aed07bbc5ada12a

build:
  number: 1
  run_exports:
    # This package has been extremely stable
    # https://abi-laboratory.pro/index.php?view=timeline&l=newt
    - {{ pin_subpackage(name, max_pin='x.x') }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - autoconf
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]

  host:
    - python
    - pip
    - popt
    - slang
    - gettext
  run:
    - python

test:
  imports:
    - snack
  commands:
    - whiptail --help

about:
  home: https://fedorahosted.org/newt/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Newt is a library for color text mode, widget based user interfaces

  description: |
    Newt is a programming library for color text mode, widget based user
    interfaces.  Newt can be used to add stacked windows, entry widgets,
    checkboxes, radio buttons, labels, plain text fields, scrollbars,
    etc., to text mode user interfaces.  Newt is based on the slang library.

extra:
  recipe-maintainers:
    - mxr-conda
    - sodre
    - oblute
    - rluria14
    - matthiasdiener
