{% set name = "newt" %}
{% set version = "0.52.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://fedorahosted.org/releases/n/e/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 265eb46b55d7eaeb887fca7a1d51fe115658882dfe148164b6c49fccac5abb31

build:
  number: 2
  run_exports:
    # This package has been extremely stable
    # https://abi-laboratory.pro/index.php?view=timeline&l=newt
    - {{ pin_subpackage(name, max_pin='x.x') }}
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
  host:
    - python
    - pip
    - popt
    - slang
    - gettext
  run:
    - python

test:
  imports:
    - snack
  commands:
    - whiptail --help

about:
  home: https://fedorahosted.org/newt/
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'Newt is a library for color text mode, widget based user interfaces'

  description: |
    Newt is a programming library for color text mode, widget based user
    interfaces.  Newt can be used to add stacked windows, entry widgets,
    checkboxes, radio buttons, labels, plain text fields, scrollbars,
    etc., to text mode user interfaces.  Newt is based on the slang library.

extra:
  recipe-maintainers:
    - sodre
    - adbeda
    - oblute
    - rluria14
