{% set name = "newt" %}
{% set version = "0.52.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://fedorahosted.org/releases/n/e/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef0ca9ee27850d1a5c863bb7ff9aa08096c9ed312ece9087b30f3a426828de82

build:
  number: 1
  run_exports:
    # This package has been extremely stable
    # https://abi-laboratory.pro/index.php?view=timeline&l=newt
    - {{ pin_subpackage(name, max_pin='x.x') }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
    - autoconf
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]

  host:
    - python
    - pip
    - setuptools
    - popt
    - slang
    - gettext
  run:
    - python

test:
  imports:
    - snack
  commands:
    - whiptail --help

about:
  home: https://fedorahosted.org/newt/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Newt is a library for color text mode, widget based user interfaces

  description: |
    Newt is a programming library for color text mode, widget based user
    interfaces.  Newt can be used to add stacked windows, entry widgets,
    checkboxes, radio buttons, labels, plain text fields, scrollbars,
    etc., to text mode user interfaces.  Newt is based on the slang library.

extra:
  recipe-maintainers:
    - mxr-conda
    - sodre
    - oblute
    - rluria14
    - matthiasdiener
