{% set name = "newt" %}
{% set version = "0.52.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://fedorahosted.org/releases/n/e/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a15efa37e86610b68a942b19a138b44ccb501c234e4c82dab2f5a9b19f7c9e79

build:
  number: 0
  run_exports:
    # This package has been extremely stable
    # https://abi-laboratory.pro/index.php?view=timeline&l=newt
    - {{ pin_subpackage(name, max_pin='x.x') }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
  host:
    - python
    - pip
    - popt
    - slang
    - gettext
  run:
    - python

test:
  imports:
    - snack
  commands:
    - whiptail --help

about:
  home: https://fedorahosted.org/newt/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Newt is a library for color text mode, widget based user interfaces

  description: |
    Newt is a programming library for color text mode, widget based user
    interfaces.  Newt can be used to add stacked windows, entry widgets,
    checkboxes, radio buttons, labels, plain text fields, scrollbars,
    etc., to text mode user interfaces.  Newt is based on the slang library.

extra:
  recipe-maintainers:
    - mxr-conda
    - sodre
    - adbeda
    - oblute
    - rluria14
