travis:
  secure:
    BINSTAR_TOKEN: UCvrGnG+Hq3C3HZ01JktsFh0ulsyAKzZocrBdY3cIsavWFkofT4l7r1OdvEminllYvlLhaNwSg6w0ABygkBD4Jpk+JjVxV8Nr890wVRecpBU2LyBc8DBOgp6qplbOt09omzd6B0AcfUkzhd5sQvLZcGhOZgR7UHI3M+wOKGvzR1yiMyzeO0aygnUGPIoAKB4LMbGV9Q7FNWe4dv/ToEDtSHYZOo87dWgIDae43DDxIRS0O6IU89UCtR/d44ysDDXC9Ey8bDvoV8Kmd+6ALyQXXdDzQI7d2k95dzw4tbHS4uJGFp+Waj1HHvBBXioO8a7fCjS+5Mcmq/+DvfdNM+r8RNSyC8zLd8XWLmB0Cy3eoqW/47+nbVri/Fp/VkcSgPOhAsVSzLz/TQFH2rstZS6OMyqF+dXRNMYmshh9fvaiqzVHUjfK4yRREP/NuJxHs7pYEAnGn4+20jnB/tdt83m7kkvaXqM8+olEm9LUv0msCPvPcDkL25F6CLC0bm4gPkjDUIBGrXQm/VaX1iWtQa0ZYSCR+jvPMl+VJF/9FsbbADssLEfm0ZCKbYx7OUfbgROX9fBnJSSXL+OEqHDntfNeFDebNEBtbRvH2N3s8+US5UzIPo8sfghUv57nIyQ46cpOMAQsAKuR3EeGbWH+hIQlnC3aw3zffYEfiEo5LjXMds=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
